-- ParoHod 2.1: non-destructive, idempotent catalogue import.
-- Existing rows (including edits and photos) are never overwritten.
-- Availability defaults to 0 until administrator confirms stock.
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Солевая монашка','Жидкости',450,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Солевая монашка' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Злая монашка','Жидкости',500,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Злая монашка' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'DUALL X Злая монашка','Жидкости',500,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'DUALL X Злая монашка' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'ISTERIKA X Самоубийца','Жидкости',500,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'ISTERIKA X Самоубийца' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'ISTERIKA CLASSIC','Жидкости',450,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'ISTERIKA CLASSIC' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Грех X ISTERIKA','Жидкости',450,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Грех X ISTERIKA' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Rick and Morty Bad Acid','Жидкости',500,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Rick and Morty Bad Acid' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'ICE FOX extra hard','Жидкости',550,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'ICE FOX extra hard' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Картридж Xros 0.6','Расходники',250,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Картридж Xros 0.6' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Картридж Xros 0.8','Расходники',250,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Картридж Xros 0.8' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Картридж Xros 0.4','Расходники',250,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Картридж Xros 0.4' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Картридж Pasito K-5','Расходники',250,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Картридж Pasito K-5' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Xros 6','Устройства',2300,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Xros 6' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Xros 6 mini','Устройства',1600,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Xros 6 mini' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Xros 5 mini','Устройства',1500,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Xros 5 mini' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Xros mini','Устройства',1100,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Xros mini' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'AEGIS BOOST 3 KIT','Устройства',2600,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'AEGIS BOOST 3 KIT' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Aegis Nano 3','Устройства',2200,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Aegis Nano 3' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Aegis Hero 5 Racing','Устройства',2500,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Aegis Hero 5 Racing' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Aegis H45 Classic','Устройства',2300,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Aegis H45 Classic' COLLATE NOCASE); 
INSERT INTO products (name,category,price,description,image_url,available,published) SELECT 'Pasito 3','Устройства',3000,'','',0,1 WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Pasito 3' COLLATE NOCASE); 
