import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {webcrypto} from 'node:crypto';
import worker from '../worker/index.js';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const token='123456:LOCAL_TEST_TOKEN';
async function sign(id){const s=new URLSearchParams({auth_date:String(Math.floor(Date.now()/1000)),user:JSON.stringify({id,first_name:'Иван',username:'tester'})});const h=async(k,v)=>{const key=await crypto.subtle.importKey('raw',k,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(v)))};const k=await h(new TextEncoder().encode('WebAppData'),token);s.set('hash',Buffer.from(await h(k,[...s].map(([a,b])=>`${a}=${b}`).sort().join('\n'))).toString('hex'));return 'tma '+s.toString()}
class DB{constructor(){this.rows=[{id:1,name:'Солевая монашка',category:'Жидкости',published:1,available:0,price:450,image_url:'',description:''}];this.photos=new Map([[1,'UPLOADED-PHOTO']]);this.visitors=new Map();this.requests=[];this.updates=0}prepare(sql){const db=this,bind=[];return {bind(...a){bind.push(...a);return this},async first(){if(sql.includes('FROM availability_inquiries WHERE telegram_id'))return db.requests.filter(x=>x.telegram_id===bind[0]).at(-1)||null;if(sql.includes('COUNT(*) n FROM availability_inquiries'))return {n:db.requests.length};if(sql.includes('SELECT id FROM products'))return db.rows.find(x=>x.id===bind[0]);if(sql.includes('SELECT\n    (SELECT COUNT'))return {visitors:db.visitors.size,new7:db.visitors.size,active30:db.visitors.size,inquiries:db.requests.length};return null},async all(){if(sql.includes('WHERE published=1 AND id IN'))return {results:db.rows.filter(x=>bind.includes(x.id))};if(sql.includes('SELECT product_id'))return {results:[]};return {results:db.rows}},async run(){if(sql.startsWith('UPDATE products SET available=')){db.updates++;for(const p of db.rows)if(p.available!==bind[0])p.available=bind[0];return {meta:{changes:1}}}if(sql.startsWith('INSERT INTO app_visitors')){db.visitors.set(bind[0],true);return {meta:{changes:1}}}if(sql.startsWith('INSERT INTO availability_inquiries')){db.requests.push({telegram_id:bind[0],created_at:'2026-09-30 00:00:00'});return {meta:{changes:1}}}return {meta:{changes:0}}}}}}
const db=new DB();const env={DB:db,BOT_TOKEN:token,ADMIN_IDS:'8204734421,5094075415',ASSETS:{fetch:async()=>new Response('html')}};
const invoke=async(path,auth,method='GET',data)=>worker.fetch(new Request('https://test.local'+path,{method,headers:{...(auth?{Authorization:auth}:{}),...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})}),env);
test('2.5 migration adds tables without touching products or uploaded photos',()=>{const s=fs.readFileSync(new URL('../upgrade_2_5.sql',import.meta.url),'utf8');assert.match(s,/CREATE TABLE IF NOT EXISTS app_visitors/);assert.match(s,/CREATE TABLE IF NOT EXISTS availability_inquiries/);assert.doesNotMatch(s,/DROP\s+TABLE|DELETE\s+FROM|ALTER\s+TABLE\s+product|UPDATE\s+products|BEGIN\s+TRANSACTION/i)});
test('mass availability action requires signed admin and explicit confirmation, preserving photos',async()=>{const plain=await sign(1111),admin=await sign(8204734421);assert.equal((await invoke('/api/admin/availability',plain,'PUT',{available:true,confirm:'ALL_PRODUCTS'})).status,403);assert.equal((await invoke('/api/admin/availability',admin,'PUT',{available:true})).status,400);assert.equal((await invoke('/api/admin/availability',admin,'PUT',{available:true,confirm:'ALL_PRODUCTS'})).status,200);assert.equal(db.rows[0].price,450);assert.equal(db.photos.get(1),'UPLOADED-PHOTO');assert.equal(db.updates,1)});
test('analytics requires authenticated Telegram and admin to view',async()=>{assert.equal((await invoke('/api/me','')).status,401);const user=await sign(1111);assert.equal((await invoke('/api/me',user)).status,200);assert.equal(db.visitors.size,1);assert.equal((await invoke('/api/admin/stats',user)).status,403);const admin=await sign(5094075415);assert.equal((await invoke('/api/admin/stats',admin)).status,200)});
test('availability inquiry validates selected IDs and Telegram, sends only information to two admins',async()=>{let sent=[];const old=globalThis.fetch;globalThis.fetch=async(u,o)=>{sent.push(JSON.parse(o.body));return new Response(JSON.stringify({ok:true}),{status:200})};try{const user=await sign(2222);assert.equal((await invoke('/api/inquiries','','POST',{ids:[1]})).status,401);assert.equal((await invoke('/api/inquiries',user,'POST',{ids:[1,1]})).status,400);assert.equal((await invoke('/api/inquiries',user,'POST',{ids:[987]})).status,409);const r=await invoke('/api/inquiries',user,'POST',{ids:[1]});assert.equal(r.status,200);assert.equal((await r.json()).delivered,2);assert.equal(sent.length,2);assert.ok(sent.every(m=>m.text.includes('запрос наличия (не заказ)')));assert.ok(sent.every(m=>!m.text.includes('доставкa')));assert.equal(db.photos.get(1),'UPLOADED-PHOTO')}finally{globalThis.fetch=old}});
test('category icons are distinct inline SVGs on both screens',()=>{const h=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');for(const id of ['drop','device','cartridge']){assert.match(h,new RegExp(`<symbol id="i-${id}"`));const body=h.match(new RegExp(`<symbol id="i-${id}"[^>]*>(.*?)<\\/symbol>`,'s'))?.[1];assert.ok(body?.length>80)}const js=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');assert.match(js,/categoryTiles/)});
