import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';import worker,{__test} from '../worker/index.js';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const token='123456:TEST_TELEGRAM_BOT_TOKEN';const admins='8204734421,5094075415';
async function sign(id,extra={}){
 const u=JSON.stringify({id,first_name:'Тест'}),s=new URLSearchParams({auth_date:String(Math.floor(Date.now()/1000)),user:u,...extra});
 const h=async(k,v)=>{const key=await crypto.subtle.importKey('raw',k,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(v)))};
 const secret=await h(new TextEncoder().encode('WebAppData'),token);
 const hash=await h(secret,[...s].map(([k,v])=>`${k}=${v}`).sort().join('\n'));
 s.set('hash',Buffer.from(hash).toString('hex'));return 'tma '+s.toString();
}
class FakeDB{
 constructor(){this.rows=[{id:1,name:new TextDecoder('windows-1251').decode(new TextEncoder().encode('Солевая монашка')),category:new TextDecoder('windows-1251').decode(new TextEncoder().encode('Жидкости')),description:'',price:450,image_url:'',available:0,published:1},{id:2,name:'Xros 6',category:'Устройства',description:'',price:2300,image_url:'',available:0,published:1}];this.photos=new Map()}
 prepare(sql){const db=this,params=[];return {bind(...args){params.push(...args);return this},async all(){if(sql.includes('SELECT product_id'))return {results:[...db.photos].map(([id,v])=>({product_id:id,updated_at:v.updated_at}))};return {results:db.rows.filter(x=>!sql.includes('WHERE published=1')||x.published).map(x=>({...x}))}},async first(){if(sql.includes('FROM product_photos'))return db.photos.get(params[0])||null;return db.rows.find(x=>x.id===params[0])||null},async run(){if(sql.includes('CREATE TABLE'))return {meta:{changes:0}};if(sql.startsWith('INSERT INTO product_photos')){db.photos.set(params[0],{data_url:params[1],updated_at:'2026-09-30'});return {meta:{changes:1}}}if(sql.startsWith('DELETE FROM product_photos')){db.photos.delete(params[0]);return {meta:{changes:1}}}if(sql.startsWith('UPDATE products SET name=?,category=?,description=?')){let x=db.rows.find(x=>x.id===params[3]);Object.assign(x,{name:params[0],category:params[1],description:params[2]});return {meta:{changes:1}}}if(sql.startsWith('UPDATE products SET')){let x=db.rows.find(x=>x.id===params[7]);if(!x)return {meta:{changes:0}};Object.assign(x,{name:params[0],category:params[1],price:params[2],description:params[3],image_url:params[4],available:params[5],published:params[6]});return {meta:{changes:1}}}return {meta:{changes:0}}}}}
}
const db=new FakeDB(),env={BOT_TOKEN:token,ADMIN_IDS:admins,DB:db,ASSETS:{fetch:async()=>new Response('ok',{headers:{'Content-Type':'text/html'}})}};
const call=(path,method='GET',auth='',body)=>worker.fetch(new Request('https://test.example'+path,{method,headers:{...(auth?{Authorization:auth}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})}),env);
test('public catalog displays restored UTF-8 name and original price',async()=>{const r=await call('/api/products');assert.equal(r.status,200);const d=await r.json();assert.equal(d[0].name,'Солевая монашка');assert.equal(d[0].category,'Жидкости');assert.equal(d[0].price,450);assert.equal(d[0].image_url,'')});
test('anonymous access to admin denied',async()=>{assert.equal((await call('/api/admin/products')).status,403);assert.equal((await call('/api/me')).status,401)});
test('both admin IDs pass, unknown ID is denied',async()=>{for(const id of [8204734421,5094075415]){const r=await call('/api/me','GET',await sign(id));assert.equal(r.status,200);assert.equal((await r.json()).admin,true)}const other=await call('/api/me','GET',await sign(9999));assert.equal((await other.json()).admin,false)});
test('tampered and expired signed payloads rejected',async()=>{const ok=await sign(8204734421);const bad=ok.replace('8204734421','0000000000');assert.equal((await call('/api/me','GET',bad)).status,401);assert.equal((await call('/api/me','GET',await sign(8204734421,{auth_date:'1'}))).status,401)});
test('admin can repair names while preserving price',async()=>{const auth=await sign(8204734421);const r=await call('/api/admin/repair-encoding','POST',auth,{});assert.equal((await r.json()).changed,1);assert.equal(db.rows[0].name,'Солевая монашка');assert.equal(db.rows[0].price,450)});
test('compressed media upload, view and delete limited to admin',async()=>{const auth=await sign(5094075415);const data='data:image/webp;base64,'+Buffer.from('RIFF_FAKE_WEBP').toString('base64');assert.equal((await call('/api/admin/images/1','POST','',{data})).status,403);assert.equal((await call('/api/admin/images/1','POST',auth,{data})).status,200);const p=(await(await call('/api/products')).json())[0];assert.match(p.image_url,/^\/api\/images\/1/);const r=await call('/api/images/1');assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/webp');assert.equal((await r.arrayBuffer()).byteLength,14);assert.equal((await call('/api/admin/images/1','DELETE',auth)).status,204);assert.equal((await call('/api/images/1')).status,404)});
test('no checkout or purchase endpoint',async()=>{const r=await call('/api/checkout','POST',await sign(8204734421),{});assert.equal(r.status,404)});
